# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fe789bc99768f995ce7d03ffcdbb7f0308bf71652ec233b9c8b62922331476356226eb1f1506443845f04206d1de792ab4d92e5948d87952099c28265969227

test:
  secret_key_base: b73112183d24b36b9e95e9ee3ea9470722515516681f03894e14fda898676849a526369c3fb64ec6e22084543c919dee9f8628ff522db83223cd1bc649f1d95d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
